### ISSUE TITLE
Popping from an empty array results in a panic

### ISSUE THREAD

**Issue by skx** [lucasepe/g2d#2]
```
▶▶ pop([]);
panic: runtime error: slice bounds out of range [:-1]

goroutine 1 [running]:
github.com/lucasepe/g2d/gg.(*Context).Pop(...)
	/home/skx/g2d/gg/context.go:1071
github.com/lucasepe/g2d/builtins/graphics.Pop(0xc0000a8090, 0xc000098b70, 0x1, 0x1, 0x0, 0x1)
	/home/skx/g2d/builtins/graphics/context.go:221 +0x24a
github.com/lucasepe/g2d/eval.applyFunction(0x58f4c3, 0x1, 0x3, 0xc0000b00e0, 0x1, 0xc0000a8090, 0x5c3cf8, 0xc0000d4540, 0xc000098b70, 0x1, ...)
	/home/skx/g2d/eval/eval.go:680 +0x292
github.com/lucasepe/g2d/eval.Eval(0x5c25b0, 0xc00006c0f0, 0xc0000a8090, 0x5c25b0, 0xc00006c0f0)
	/home/skx/g2d/eval/eval.go:174 +0x29f
github.com/lucasepe/g2d/eval.Eval(0x5c25d8, 0xc0000d6300, 0xc0000a8090, 0x5c25d8, 0xc0000d6300)
	/home/skx/g2d/eval/eval.go:105 +0x18b8
github.com/lucasepe/g2d/eval.evalProgram(0xc0000a80d8, 0xc0000a8090, 0x56c6a0, 0x0)
	/home/skx/g2d/eval/eval.go:274 +0xc7
github.com/lucasepe/g2d/eval.Eval(0x5c27b8, 0xc0000a80d8, 0xc0000a8090, 0xc0000b00c8, 0x8)
	/home/skx/g2d/eval/eval.go:101 +0xbd
github.com/lucasepe/g2d/repl.(*REPL).StartEvalLoop(0xc0000c1f48, 0x5c1728, 0xc0000b4000, 0x5c1748, 0xc0000b4008, 0xc0000a8090)
	/home/skx/g2d/repl/repl.go:107 +0x1c7
github.com/lucasepe/g2d/repl.(*REPL).Run(0xc0000c1f48)
	/home/skx/g2d/repl/repl.go:124 +0x5ba
main.main()
	/home/skx/g2d/main.go:87 +0x465
```

**Comment by skx** [comment]
I thought `pop` was relating to arrays, like `append`.  But it seems it is actually a graphics-primitive.  So it shouldn't panic, but it seems like this is less likely to happen by accident :)

**Comment by lucasepe** [comment]
this happens because you invoked `pop(...)` without first invoking `push()` (and the stack was nil) ... thanks! 
I would never have gotten there - fixed I'll release it with the next version
